# Netlify Configuration for AI Platform Frontend - Updated

[build]
  # Build command for Next.js static export
  base = "frontend-next"
  command = "npm install && npm run build"
  
  # Output directory (Next.js static export)
  publish = "out"
  
  # Functions directory (if needed later)
  functions = "netlify/functions"

[build.environment]
  # Node.js version
  NODE_VERSION = "20"
  
  # Next.js configuration
  NEXT_TELEMETRY_DISABLED = "1"

# Redirect rules for SPA routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  conditions = {Role = ["admin"], Country = ["US"]}

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval'; style-src 'self' 'unsafe-inline'; img-src 'self' data: https:; font-src 'self' data:; connect-src 'self' https://api.anthropic.com https://api.openai.com"

# Cache static assets
[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/_next/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Environment-specific settings
[context.production]
  base = "frontend-next"
  command = "npm install && npm run build"
  
[context.deploy-preview]
  base = "frontend-next"
  command = "npm install && npm run build"

[context.branch-deploy]
  base = "frontend-next"
  command = "npm install && npm run build"

# Plugin configurations
[[plugins]]
  package = "@netlify/plugin-nextjs"

# Forms handling (if needed)
[forms]
  # Enable Netlify Forms
  
# Edge functions (if needed in future)
# [[edge_functions]]
#   path = "/api"
#   function = "api-handler"