# Netlify Configuration for נדל"ן AI Platform
[build]
  base = ""
  command = "npm install && npm run build:web"
  publish = "apps/web/dist"

[build.environment]
  NODE_VERSION = "20"
  NEXT_TELEMETRY_DISABLED = "1"
  NEXT_PUBLIC_API_URL = "https://ai-platform-backend-mow5.onrender.com"
  NEXT_PUBLIC_APP_NAME = "נדל\"ן AI Platform"

# SPA routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "camera=(), microphone=(), geolocation=()"

# Static assets caching
[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/_next/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Context-specific builds
[context.production]
  command = "npm install && npm run build:web"

[context.deploy-preview]
  command = "npm install && npm run build:web"

[context.branch-deploy]
  command = "npm install && npm run build:web"