services:
  - type: web
    name: ai-platform-backend
    env: node
    buildCommand: |
      npm install
      cd apps/api
      npm install
      npm run build
      npx prisma generate
      node scripts/setup-database.js
    startCommand: cd apps/api && npm start
    plan: free
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: ai-platform-db
          property: connectionString
      - key: OPENAI_API_KEY
        value: sk-xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
      - key: ANTHROPIC_API_KEY
        value: sk-ant-apixxxxxxxxxxxxxxxxxxxxxxxxx
      - key: GEMINI_API_KEY
        value: AIzaxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
