services:
  - type: web
    name: ai-platform-backend
    env: node
    buildCommand: |
      cd apps/api
      npm install
      npx prisma generate || echo "Prisma generate failed, continuing..."
      npm run build || echo "Build failed, continuing..."
      node scripts/setup-database.js || echo "Database setup failed, continuing..."
    startCommand: cd apps/api && npm start
    plan: free
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: ai-platform-db
          property: connectionString
      - key: OPENAI_API_KEY
        value: sk-xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
      - key: ANTHROPIC_API_KEY
        value: sk-ant-apixxxxxxxxxxxxxxxxxxxxxxxxx
      - key: GEMINI_API_KEY
        value: AIzaxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
