services:
  - type: web
    name: ai-platform-backend
    env: node
    buildCommand: |
      npm install
      cd apps/api && npm install
      cd apps/api && npm run build
      cd apps/api && npx prisma generate
      cd apps/api && node dist/scripts/setup-database.js || echo "Database setup failed, continuing..."
    startCommand: cd apps/api && node dist/index.js
    plan: free
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: ai-platform-db
          property: connectionString
      - key: OPENAI_API_KEY
        value: sk-xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
      - key: ANTHROPIC_API_KEY
        value: sk-ant-apixxxxxxxxxxxxxxxxxxxxxxxxx
      - key: GEMINI_API_KEY
        value: AIzaxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
