services:
  # Backend API Service - נדל"ן AI Platform
  - type: web
    name: nedlan-ai-backend
    runtime: node
    plan: free
    rootDir: apps/api
    buildCommand: npm install && npm run build
    startCommand: npm start
    healthCheckPath: /health
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: CORS_ORIGIN
        value: https://super-genie-7460e3.netlify.app
      - key: DATABASE_URL
        fromDatabase:
          name: nedlan-ai-db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_EXPIRE
        value: "24h"
      - key: ANTHROPIC_API_KEY
        sync: false
      - key: GOOGLE_AI_API_KEY
        sync: false
      - key: OPENAI_API_KEY
        sync: false

databases:
  # PostgreSQL Database
  - name: nedlan-ai-db
    plan: free