services:
  # Backend API Service
  - type: web
    name: nedlan-ai-api
    runtime: node
    plan: free
    rootDir: apps/api
    buildCommand: npm install && npm run build:api
    startCommand: npm start
    healthCheckPath: /health
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: CORS_ORIGIN
        value: https://super-genie-7460e3.netlify.app
      - key: DATABASE_URL
        fromDatabase:
          name: ai-platform-db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_EXPIRE
        value: "24h"
      - key: JWT_REFRESH_EXPIRE
        value: "7d"
      - key: ENCRYPTION_KEY
        generateValue: true
      - key: SESSION_SECRET
        generateValue: true
      - key: RATE_LIMIT_WINDOW_MS
        value: "900000"
      - key: RATE_LIMIT_MAX_REQUESTS
        value: "100"
      - key: MCP_SERVERS_PATH
        value: "./mcp-servers"
      - key: MCP_DEFAULT_TIMEOUT
        value: "30000"
      - key: ENABLE_METRICS
        value: "true"
      - key: METRICS_PORT
        value: "9090"
      - key: ANTHROPIC_API_KEY
        sync: false
      - key: GOOGLE_AI_API_KEY
        sync: false
      - key: OPENAI_API_KEY
        sync: false

databases:
  # PostgreSQL Database
  - name: ai-platform-db
    plan: free